// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTr0Yn7AXhybBbP4QPvEFLTXHhWlyLCAU',
    appId: '1:844183542062:web:995e8dc92407f45c1e82bf',
    messagingSenderId: '844183542062',
    projectId: 'auth-exam-firebase-1',
    authDomain: 'auth-exam-firebase-1.firebaseapp.com',
    storageBucket: 'auth-exam-firebase-1.appspot.com',
    measurementId: 'G-7Y0X9P9WN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7EmtoMFwZlTPVDmX9eJxXIWlz2slQyBE',
    appId: '1:844183542062:android:c69cca4aec1cfa881e82bf',
    messagingSenderId: '844183542062',
    projectId: 'auth-exam-firebase-1',
    storageBucket: 'auth-exam-firebase-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXy7-X5F15oCkNZ-A68pOIHO28KjFRHTQ',
    appId: '1:844183542062:ios:fc3085f2a82b2c761e82bf',
    messagingSenderId: '844183542062',
    projectId: 'auth-exam-firebase-1',
    storageBucket: 'auth-exam-firebase-1.appspot.com',
    iosBundleId: 'com.example.authexamFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXy7-X5F15oCkNZ-A68pOIHO28KjFRHTQ',
    appId: '1:844183542062:ios:fc3085f2a82b2c761e82bf',
    messagingSenderId: '844183542062',
    projectId: 'auth-exam-firebase-1',
    storageBucket: 'auth-exam-firebase-1.appspot.com',
    iosBundleId: 'com.example.authexamFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTr0Yn7AXhybBbP4QPvEFLTXHhWlyLCAU',
    appId: '1:844183542062:web:2353c8a59cb0b8b91e82bf',
    messagingSenderId: '844183542062',
    projectId: 'auth-exam-firebase-1',
    authDomain: 'auth-exam-firebase-1.firebaseapp.com',
    storageBucket: 'auth-exam-firebase-1.appspot.com',
    measurementId: 'G-QYWE8NLQEL',
  );
}
